### ISSUE TITLE
About source code

### ISSUE THREAD

**Issue by zhongtao93** [barisgecer/GANFit#1]
Really a good job! Will you release the source code?

Thanks

**Comment by ghost** [comment]
also wondering about this, any update?

**Comment by WANG656384832** [comment]
i wondering about this

**Comment by MikhailBaranau** [comment]
Me too

**Comment by opptimus** [comment]
me too

**Comment by guolinjie007** [comment]
me too

**Comment by spiketg** [comment]
me too!

**Comment by Soonscut** [comment]
me too

**Comment by no-materials** [comment]
Same here!

**Comment by jurastm** [comment]
#metoo

**Comment by fjzpcmj** [comment]
me too

**Comment by xingmimfl** [comment]
me too

**Comment by angelomenezes** [comment]
me too

**Comment by noranart** [comment]
me too

**Comment by YokkaBear** [comment]
me too

**Comment by PeterZhouSZ** [comment]
me too

**Comment by mumuyanyan** [comment]
me too too too

**Comment by xuexiaoxiaohu** [comment]
Good job!
i have a question,how to get latent parameters from an image? Is from deep networks?
thanks for your apply

**Comment by barisgecer** [comment]
Hi all, I know many of you waiting quite a long time but unfortunately I have to say that the code may never be public due to IP ownership. I will write here once things get certain.

**Comment by ababilinski** [comment]
Isn't the purpose of git to share code/projects? I think Gist would be a better place to post publication information - since the repo is just a ReadMe file.

**Comment by barisgecer** [comment]
@ababilinski please see  #8
