### ISSUE TITLE
Amazing work! Would love to try out the demos!

### ISSUE THREAD

**Issue by JaeDukSeo** [barisgecer/GANFit#10]
Amazing work! Would love to try out the demos!

**Comment by barisgecer** [comment]
Hi,

Unfortunately, the method we proposed in this paper has been patented and the IP of the source code has been commercialized. Thus, personally, I cannot share the code or release public demos at this stage. I can, however, pass some images or datasets (if not very large) to be reconstructed by our approach for research purposes (comparison figures, etc.)

Kind Regards,
Baris
