### ISSUE TITLE
Texture coordinate

### ISSUE THREAD

**Issue by hanyanghong86** [barisgecer/GANFit#12]
Hi, I want to ask you about how to define the texture coordinate to correspond the 3D vertices with uv texture map, do you know any learning materials about this knowledge point.

**Comment by barisgecer** [comment]
I would have a look at pytorch3d and menpo tutorials

https://pytorch3d.org/tutorials/render_textured_meshes
https://github.com/facebookresearch/pytorch3d
https://notebook.community/menpo/menpo3d-notebooks/notebooks/Rasterization%20Basics
