### ISSUE TITLE
How to evaluate florence dataset for my model

### ISSUE THREAD

**Issue by AsiyaNaqvi** [barisgecer/GANFit#14]
Thankyou for providing the code for evaluation.

I am sorry for naive question but what I really can't understand is that of which pictures I have to predict meshes using my model.
If we generate meshes of Indoor-Cooperative, PTZ-Indoor, PTZ-Outdoor and compare it with registered ground truth meshes which are in frontal pose and neutral expression but predicted meshses will contain some pose and expression along with shape. How they are comparable with each other? How the frontal 1 or 2 is comparable with Indoor-Cooperative, PTZ-Indoor or PTZ-Outdoor.
I hope I made my point here.
What should be the file hirerichy of the predicted meshes?

**Comment by barisgecer** [comment]
What I do, is that choosing 5 random images from each video and estimate a shape per video. Then compare the estimated mesh with the ground truth (minimum of frontal-1 and frontal-2).

A good 3d face reconstruction algorithm is robust to pose and disentangle expression. You can have a look at the paper for some technical background of 3d face reconstruction, or my Ph.D. thesis.
