### ISSUE TITLE
About images of MOFA-test dataset

### ISSUE THREAD

**Issue by JesseZhang92** [barisgecer/GANFit#15]
Hi Baris, thanks for your impressive work. Currently I notice that some works would like to perform evaluation on MOFA-test dataset, mainly on the 7 images showed in GANfit. However, I struggle to find the source of these images. If possible, could you please share these 7 images to me, or tell me where I can download them? Many thanks to your help.

**Comment by barisgecer** [comment]
Send me an email and I will send them to you. I got them from MOFA authors. Alternatively, you can crop images from the paper.
