### ISSUE TITLE
How to get the ground truth and template landmarks

### ISSUE THREAD

**Issue by shubhajitbasak** [barisgecer/GANFit#16]
Thanks for sharing the evaluation code. I am trying to evaluate some other ground truth datasets like face warehouse. Just wondering how to manually annotate the template mesh? Is there any tool available for that? Also, it will be helpful if you could provide a sample of how you have generated the landmark files for the ground truths as the ground truth dataset does not have any landmarks provided on it.

**Comment by barisgecer** [comment]
https://github.com/menpo/landmarker.io
https://www.menpo.org/landmarkerio/

**Comment by shubhajitbasak** [comment]
Thank you!!
