### ISSUE TITLE
When can authors share source code and trained models?

### ISSUE THREAD

**Issue by jackspiderman** [barisgecer/GANFit#4]
The effect of this 3D face reconstruction looks better than other works. Unfortunately, the author has not shared the source code so far. I am looking forward to reproduce the results as pictures in the demo .

**Comment by xingmimfl** [comment]
If he shares the code, the author also has to share the dataset. I think, the dataset is more important than the code

**Comment by zhuhaozh** [comment]
Looking forward too

**Comment by vitahsu** [comment]
@jackspiderman how do you get the dataset first? Thanks!

**Comment by coloneldbugger** [comment]
I guess we're not going to see the code for this?

**Comment by barisgecer** [comment]
Thank you for the interest. Please see issue #1 for the answer
