### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by shoukna** [barisgecer/GANFit#7]
Hi @barisgecer, thanks for your brilliant work.

In the paper, you use the Large Scale Face Model for 3DMM shape model and the 4DFAB database.
I want to reproduce this paper, but I can not get access to these two datasets, would you please help me how I can get them?

I am looking forward to your reply!

Best regards.

**Comment by barisgecer** [comment]
Please see #2.

**Comment by shoukna** [comment]
Thanks for your reply!

Can I use BFM(Basel Face Model) to replace the LSFM dataset? And how I can get the 4DFAB dataset, which can not been found from the Internet.

What's more, I want to ask if the Large Scale Face Model(LSFM) dataset can be purchased? Our laboratory wants to use it for scientific research only.

Best regards.

**Comment by barisgecer** [comment]
Hi shouka,

Sorry for my late reply. I have been quite busy lately. First of all, I am personally neither holding the license of any of the datasets nor I am the person responsible for these datasets. But I will try to help you with the all information I have. Below my answers:

> Can I use BFM(Basel Face Model) to replace the LSFM dataset? 

Yes, you can. You can replace LSFM with BFM or any other 3D Face datasets. However, please mind that larger the dataset, more likely to generalize well.

> And how I can get the 4DFAB dataset, which can not been found from the Internet.

I am not sure about 4DFAB's public availability. But you can use any expression blend shape model to replace it. Like FaceWareHouse

> What's more, I want to ask if the Large Scale Face Model(LSFM) dataset can be purchased? Our laboratory wants to use it for scientific research only.

I am not sure about this either. You can apply to get LSFM shape model here: https://xip.uclb.com/i/healthcare_tools/LSFM.html for free. But I am not sure about the texture model. It is best to ask contacts found here: https://ibug.doc.ic.ac.uk/resources/lsfm/

Hope this helps,
Baris

**Comment by shoukna** [comment]
Thank you so much, this helps me a lot!

As a beginner to the 3D face, I am confused about the UV maps, how can I get the UV maps from 3D datasets, which are input to the GAN network to train?

This question has puzzled me for a long time, I hope you can help me, thank you!

Best regards.

**Comment by barisgecer** [comment]
Well, it is not that simple to explain on github :). Have a look at below references:


- Booth, James, Anastasios Roussos, Stefanos Zafeiriou, Allan Ponniahy, and David Dunaway. ‘A 3D Morphable Model Learnt from 10,000 Faces’. In Proceedings of the IEEE Computer Society Conference on Computer Vision and Pattern Recognition, 2016-December:5543–52, 2016. https://doi.org/10.1109/CVPR.2016.598.

- Egger, Bernhard, William A. P. Smith, Ayush Tewari, Stefanie Wuhrer, Michael Zollhoefer, Thabo Beeler, Florian Bernard, et al. ‘3D Morphable Face Models – Past, Present and Future’. ArXiv Preprint ArXiv:1909.01815, 2019. http://arxiv.org/abs/1909.01815.

- Blanz, Volker, and Thomas Vetter. ‘A Morphable Model for the Synthesis of 3D Faces’. In Proceedings of the 26th Annual Conference on Computer Graphics and Interactive Techniques, SIGGRAPH 1999, 187–94, 1999. https://doi.org/10.1145/311535.311556.

- Smith, William A. P., Alassane Seck, Hannah Dee, Bernard Tiddeman, Joshua Tenenbaum, and Bernhard Egger. ‘A Morphable Face Albedo Model’. ArXiv:2004.02711 [Cs], 6 April 2020. http://arxiv.org/abs/2004.02711.

From my point of view, they are the dataset, but it requires a lot of work to acquire UV images from raw 3D scans

**Comment by shoukna** [comment]
Many thanks for your help, I will try to get it!
