### ISSUE TITLE
unable to reproduce the result

### ISSUE THREAD

**Issue by MandyMo** [barisgecer/GANFit#8]
I am struggle to reproduce the result proposed in the paper.
While in practice, I found the GAN does not work in fact.

I really can not understand what's the purpose of this github as it can offer nothing benifical to the community.

**Comment by MandyMo** [comment]
Maybe you should delete this junk repo.

**Comment by barisgecer** [comment]
Well, your post is not beneficial for the community either, yet here we are! 😄 

Seriously, if you had a particular question, you can ask here. I have been receiving emails and issues regarding details of the paper, extra results for comparison, or even 3DMM basics. I tried my best to approach them. Nevertheless, I tried to be beneficial to the community by sharing the research that took my months with all kinds of details to be beneficial for the community.

The IP of the code and the data does not belong to me and my co-authors. Thus, we are not authorized to decide on releasing them publicly. In the beginning, this decision was not certain, so I made this repo as the 'Project page' of the paper to update any news regarding that, answering any questions about the paper or even how to implement it. I am not sure how it would bother anyone as it is immediately clear that there is no code.

If you have any images want to reconstruct in 3D, you can send me. Or if you give me some details, I can try to help why your GAN didn't work.
